# A dictionary of supported funding model platforms
funding_platforms = {
    "github": [],  # up to 4 GitHub Sponsors-enabled usernames
    "patreon": "",  # a single Patreon username
    "open_collective": "",  # a single Open Collective username
    "ko_fi": "",  # a single Ko-fi username
    "tidelift": "",  # a single Tidelift platform-name/package-name
    "community_bridge": "",  # a single Community Bridge project-name
    "liberapay": "",  # a single Liberapay username
    "issuehunt": "",  # a single IssueHunt username
    "otechie": "",  # a single Otechie username
    "custom": [],  # up to 4 custom sponsorship URLs
}
